### PR TITLE
store collapsible expand state to sessionstorage

### PR DESCRIPTION
**Pull request by neCo2**
It always bothered me that I had to re-open/close collapsibles after reloading, so I made the `collapsibleGroup` component use `sessionStorage`.

### CODE REVIEW

**Comment by neCo2** [comment]
Note to self: Fix collapsibles in modals, then it should be ready for review.

**Comment by lmg-anon** [comment]
Good idea, but I think the changes you made are overkill. It doesn't make sense to store this in the `SessionStorage` since this is more of a global configuration. Also, you could achieve the same result with just:
```javascript
function CollapsibleGroup({ label, expanded, children }) {
	const contentArea = useRef(null);
	const [isCollapsed, setIsCollapsed] = usePersistentState(`(${label}).isCollapsed`, !expanded);
	const [contentHeight, setContentHeight] = useState(isCollapsed ? 0 : '');
```
However, modals would still need some special treatment in case there are collapsible groups with the same labels inside them.

**Comment by neCo2** [comment]
Switched it to your solution and added an option to use a different name for the state with `stateLabel`.
This is definitely more elegant, but I thought it was actually nice that the Parameters and Sampling collapsibles would always open when making a new session.

If you say sessionStorage is too much, I'll trust your call on this. I don't have any particularly strong feelings here, and it's still way better than the previous behaviour.

**Comment by lmg-anon** [comment]
I think there is a different way to accomplish what you want (which isn't a bad idea). Maybe something like this:

```js
function CollapsibleGroup({ label, expanded, expand, children }) {
	const contentArea = useRef(null);
	const [contentHeight, setContentHeight] = useState(!expanded ? 0 : '');
	const [isCollapsed, setIsCollapsed] = useState(!expanded);

	if (!expand.current) {
		expand.current = (value) => setIsCollapsed(value);
	}

	...
}
...
const expandParameters = useRef();
...
<CollapsibleGroup expand={expandParameters} .../>
```

Then this could be used when a session is created to programmatically expand the collapsibles we want to expand. I guess it would be necessary to create a session creation event and then listen for that event in the `useEffect` at the bottom of the `App` component.

I will merge this PR now but feel free to open another PR if you decide to do this! Thank you for this contribution.

**Pull request merged**
