### PR TITLE
added compile workflow

### PR DESCRIPTION
**Pull request by neCo2**
A workflow that automatically builds `mikupad_compiled.html`. Feel free to close if this isn't something you want.
It runs the compile.sh script, and then automatically pushed to the repository.
I've got it running on [my main branch](https://github.com/neCo2/mikupad) if you want to see the result.

~~It kept bugging me about updating to the v4 actions and the npm version, so I did that, but for some reason it gets stuck on `Cleaning up orphan processes` for 20+ minutes now. It builds and pushes no problem, but then the action gets stuck at the end and doesn't actually complete.~~

~~It appears that this might be caused by issues with github rather than the action itself: https://github.com/orgs/community/discussions/15133#discussioncomment-5469332
firefox_2024-05-21_15-15-09~~

Everything working as intended now. Looks like it was the partial outage.

### CODE REVIEW

**Comment by lmg-anon** [comment]
I honestly can't tell if this would be useful or just annoying. Pushing to the repository feels like it would create a lot of useless commits, so I don't like that.

I guess this would work nicely if it creates new releases similarly to how it works in the llama.cpp repo. The downside is that it would have lower visibility, but this could perhaps be mitigated by mentioning it in the README.

**Comment by neCo2** [comment]
Definitely understand where you're coming from.
Rewrote it so it now creates a release. Tried making the text body of the release a bit fancy by making it show the log graph since the last change. For this, it tags every release with the number of current commits, compares it to the number of commits of the last release, then prints the `git log --graph --oneline` for the number of new commits.
For the first release it doesn't print that though, because that'd just take up too much space.
I've got it running again on my main with a few example commits if you wanna look at it.

**Comment by lmg-anon** [comment]
This looks pretty good! But I wonder what happened here: https://github.com/neCo2/mikupad/releases/tag/release337
I guess it isn't taking into consideration the commits that are part of a merge?

**Comment by neCo2** [comment]
The action just takes the difference between the number of commits (which it's putting in the tags, so in this case release337 - release336 = 1), and adds 1 to also show the most recent commit of the previous release.
And that's apparently just what it looks like when `git log --graph` ends on a merge commit.
cmd_2024-05-24_09-14-09
Don't mind the ¥, Japanese system locale does weird things to backslashes in cmd.

I thought it was a good idea just to show the "starting point" or something, but the more I look at it, the more I think it's unnecessary.

**Comment by lmg-anon** [comment]
>I thought it was a good idea just to show the "starting point" or something, but the more I look at it, the more I think it's unnecessary.

Yeah, the starting point should already be obvious if you go to the Releases page.

**Comment by lmg-anon** [comment]
Thank you for your contribution once again!

**Pull request merged**
