### PR TITLE
Allow importing multiple files at once and only keep active session in sessions object

### PR DESCRIPTION
**Pull request by saood06**
This drastically cuts down on memory usage which matters on mobile devices, and also calling /all with a mikupad server running with a lot of sessions previously would cause node.js to balloon in memory usage, and even if given the RAM the  ```res.json({ ok: true, result: all });``` would cause RangeError: Invalid string length.

This is a draft PR as it does not function with the IndexedDBAdapter, I would appreciate it if you could handle that, or at least verify that you are fine with this approach, and I'll then work on that, but I'm not very familiar with IndexedDB and couldn't see a way to efficiently handle the new operations.

### CODE REVIEW

**Comment by lmg-anon** [comment]
Yeah, this change looks very reasonable to me. I admit the server was done very lazily, I never thought this would be a problem to the point of causing errors lol

>I would appreciate it if you could handle that, or at least verify that you are fine with this approach

I can handle it, just try to make sure the IndexedDB still works so I can merge the PR.

**Comment by saood06** [comment]
>I admit the server was done very lazily, I never thought this would be a problem to the point of causing errors lol

The whole motivation for this was that I kept hitting out of memory errors in the browser that would break mikupad mid prediction. I only ran into the server errors later.

> I can handle it, when you think you're finished you can make the PR ready for review.

I added the needed stuff into IndexedDBAdapter to make it functional, so it's now ready to review. I confirmed IndexedDB doesn't have an efficient way to handle the new operations so no performance for it with this PR unlike ServerDBAdapter. A new DBAdapter based on wa-sqlite or the official sqlite wasm might function better than the IndexedDBAdapter, and would also have the benefit of sharing all the SQL queries with the server implementation. I've been thinking about adding branching support, and I think that would matter there.

Also two more things, mikupad should probably request permission to use persistent storage and while testing this I saw `Uncaught TypeError: e.stopImmediatePropagation is not a function` that occurs when confirming or denying a session rename.

**Comment by lmg-anon** [comment]
>I added the needed stuff into IndexedDBAdapter to make it functional, so it's now ready to review.

The changes LGTM!

>I confirmed IndexedDB doesn't have an efficient way to handle the new operations so no performance benefit for it with this PR unlike ServerDBAdapter. A new DBAdapter based on wa-sqlite or the official sqlite wasm might function better than the IndexedDBAdapter, and would also have the benefit of sharing all the SQL queries with the server implementation.

Sharing code between the frontend and backend is tempting, but I feel like it's overkill to include WebAssembly in this project just for this purpose. Too bad WebSQL was deprecated; it would probably be a good fit.
But in any case, I think a good way to improve the IndexedDB implementation, given the limitations present, would be to have a separate objectStore exclusively for session prompts, since it's probably the heaviest. This could be done in another occasion.

**Comment by lmg-anon** [comment]
>mikupad should probably request permission to use persistent storage and while testing this I saw Uncaught TypeError: e.stopImmediatePropagation is not a function that occurs when confirming or denying a session rename.

I almost missed this, thanks, I will take a look at it! Although, it looks like Chromium-based browsers don't allow you to request persistent storage, rather, they grant it to the web app according to some criteria... That's weird.

**Comment by saood06** [comment]
The situation is still a lot better now (mobile is actually usable now whereas previously just loading mikupad would just OOM and crash, and on desktop I haven't encountered an out of memory error mid generation), but it turns out even with this change where only the active session should be held in memory, Firefox seems to sometimes "leak" memory resulting in the mikupad tab consuming GBs of memory again, and in order to reclaim that memory you have to unload the process containing that tab and then reloading mikupad where it will go back to consuming a more reasonable amount of memory. I do think this is a firefox GC issue, and not a mikupad issue at this point.

>I think a good way to improve the IndexedDB implementation, given the limitations present, would be to have a separate objectStore exclusively for session prompts, since it's probably the heaviest. This could be done in another occasion.

I might actually implement this soon for the server backend, as my cold start time for mikupad is now in the minutes, and separating out the session prompts in the server backend should help deal with that as the /sessions endpoint currently does gigabytes of disk I/O which should reduce drastically once the prompts are separate. 

I've been putting off doing this as I thought I wanted to implement branching and parallel generation, both of which would require a lot of refactoring, but I haven't finalized out all the details of how either implementation should be done yet.

>Too bad WebSQL was deprecated; it would probably be a good fit.

It was deprecated, but from what I've heard they waited to kill it until an alternative came around and sqlite wasm is the alternative that they even recommend migrating to in this [article](https://developer.chrome.com/blog/from-web-sql-to-sqlite-wasm). It is still your call if you don't want WebAssembly here, I don't really care as I primarily use the server backend and not IndexedDB anyway.

**Comment by saood06** [comment]
> But in any case, I think a good way to improve the IndexedDB implementation, given the limitations present, would be to have a separate objectStore exclusively for session prompts, since it's probably the heaviest. This could be done in another occasion.

I ended up going with an objectStore exclusively for the session names (this removes the json functions for renaming and listing sessions). My work isn't ready for a PR yet but this change alone reduced launch time from minutes to seconds for my large database file.

The size of the database file itself is also something that I'm working on addressing. If I store it on a filesystem that does transparent LZ4 compression then I can see a 2-4x reduction in size, but using sqlite-zstd I can achieve above 10x reduction.

With both of these changes mikupad goes back to being much more manageable to use. I'll share my work with PR's when it is ready, but this time I may not fix IndexedDB (since my changes will break it), sorry.

**Pull request merged**
